spring:
  application:
    name: Movie_API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_db
    password: 12345
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081

omdb:
  api:
    key: a3f451ca
    url: http://www.omdbapi.com/


# Local file storage configuration
file:
  upload-dir: src/main/resources/uploads/products